-- HOMES 20周年アプリ v4.7
-- 1回実行してください。投稿情報 + 軽量サムネイル用 Storage の設定です。

create table if not exists public.anniversary_posts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  email text,
  title text not null,
  author_name text,
  campus text,
  category text,
  drive_file_id text,
  preview_url text,
  is_public boolean not null default false,
  final_movie_candidate boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.anniversary_posts alter column user_id drop not null;
alter table public.anniversary_posts alter column email drop not null;
alter table public.anniversary_posts enable row level security;

drop policy if exists "homes staff can read posts" on public.anniversary_posts;
drop policy if exists "homes staff can create own posts" on public.anniversary_posts;
drop policy if exists "homes staff can update own posts" on public.anniversary_posts;
drop policy if exists "anniversary app can create posts" on public.anniversary_posts;
drop policy if exists "anniversary app can read posts" on public.anniversary_posts;

create policy "anniversary app can create posts"
on public.anniversary_posts
for insert
to anon
with check (is_public = false);

create policy "anniversary app can read posts"
on public.anniversary_posts
for select
to anon
using (true);

grant insert, select on table public.anniversary_posts to anon;

-- 軽量プレビュー専用。原本写真・動画はここには置かず、後で会社Google Driveへ保存します。
insert into storage.buckets (id, name, public)
values ('anniversary-previews', 'anniversary-previews', true)
on conflict (id) do update set public = true;

drop policy if exists "anniversary previews are public" on storage.objects;
drop policy if exists "anniversary app can upload previews" on storage.objects;

create policy "anniversary previews are public"
on storage.objects
for select
to public
using (bucket_id = 'anniversary-previews');

create policy "anniversary app can upload previews"
on storage.objects
for insert
to anon
with check (bucket_id = 'anniversary-previews');

-- v5.0: Google Drive原本の管理情報
alter table public.anniversary_posts add column if not exists drive_web_view_url text;
alter table public.anniversary_posts add column if not exists original_file_name text;
alter table public.anniversary_posts add column if not exists original_mime_type text;
alter table public.anniversary_posts add column if not exists original_size bigint;


-- HOMES 20周年アプリ v5.8 追加設定
-- ログインボーナス / 表彰集計 / KENJI MODE「今日は何の日」追加用
-- Supabase SQL Editor で1回だけ実行してください。

create table if not exists public.anniversary_login_days (
  id bigint generated by default as identity primary key,
  staff_name text not null,
  login_date date not null,
  device_id text,
  created_at timestamptz not null default now(),
  unique (staff_name, login_date)
);

alter table public.anniversary_login_days enable row level security;
drop policy if exists "anniversary app can read login days" on public.anniversary_login_days;
drop policy if exists "anniversary app can create login days" on public.anniversary_login_days;
create policy "anniversary app can read login days"
on public.anniversary_login_days for select to anon using (true);
create policy "anniversary app can create login days"
on public.anniversary_login_days for insert to anon with check (true);
grant select, insert on table public.anniversary_login_days to anon;
grant usage, select on sequence public.anniversary_login_days_id_seq to anon;

create table if not exists public.anniversary_today_events (
  id uuid primary key default gen_random_uuid(),
  month smallint not null check (month between 1 and 12),
  day smallint not null check (day between 1 and 31),
  event_year integer,
  title text not null,
  note text,
  author_name text,
  created_at timestamptz not null default now()
);

alter table public.anniversary_today_events enable row level security;
drop policy if exists "anniversary app can read today events" on public.anniversary_today_events;
drop policy if exists "kenji can create today events" on public.anniversary_today_events;
create policy "anniversary app can read today events"
on public.anniversary_today_events for select to anon using (true);
create policy "kenji can create today events"
on public.anniversary_today_events for insert to anon with check (true);
grant select, insert on table public.anniversary_today_events to anon;

-- Post count is taken from the existing anniversary_posts table.
-- Login counts start accumulating after v5.8 is deployed.
-- HOMES 20周年アプリ v5.14
-- 計測基盤 / 表彰ダッシュボード / 社員名簿 / お知らせ / FINAL MOVIE管理
-- Supabase SQL Editorで1回実行してください。

alter table public.anniversary_posts add column if not exists media_kind text;
alter table public.anniversary_posts add column if not exists media_width integer;
alter table public.anniversary_posts add column if not exists media_height integer;
alter table public.anniversary_posts add column if not exists media_duration_seconds numeric;
alter table public.anniversary_posts add column if not exists is_portrait boolean;
alter table public.anniversary_posts add column if not exists final_movie_status text not null default 'unreviewed';
alter table public.anniversary_posts add column if not exists final_movie_note text;

create table if not exists public.anniversary_activity_events (
  id bigint generated by default as identity primary key,
  staff_name text not null,
  event_type text not null,
  event_date date not null default ((timezone('Asia/Tokyo', now()))::date),
  device_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists anniversary_activity_staff_idx on public.anniversary_activity_events(staff_name);
create index if not exists anniversary_activity_type_idx on public.anniversary_activity_events(event_type);
create index if not exists anniversary_activity_created_idx on public.anniversary_activity_events(created_at);
alter table public.anniversary_activity_events enable row level security;
drop policy if exists "anniversary app can create activity events" on public.anniversary_activity_events;
create policy "anniversary app can create activity events" on public.anniversary_activity_events for insert to anon with check (true);
grant insert on table public.anniversary_activity_events to anon;
grant usage, select on sequence public.anniversary_activity_events_id_seq to anon;

create table if not exists public.anniversary_staff_roster (
  id bigint generated by default as identity primary key,
  staff_name text not null unique,
  campus text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.anniversary_staff_roster enable row level security;

create table if not exists public.anniversary_announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text,
  is_active boolean not null default true,
  start_at timestamptz,
  end_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.anniversary_announcements enable row level security;
drop policy if exists "anniversary app can read announcements" on public.anniversary_announcements;
create policy "anniversary app can read announcements" on public.anniversary_announcements
for select to anon using (
  is_active = true
  and (start_at is null or start_at <= now())
  and (end_at is null or end_at >= now())
);
grant select on table public.anniversary_announcements to anon;

-- 管理APIはService Role経由で上記テーブルを操作します。
