-- HOMES 20周年アプリ v5.14
-- 計測基盤 / 表彰ダッシュボード / 社員名簿 / お知らせ / FINAL MOVIE管理
-- Supabase SQL Editorで1回実行してください。

alter table public.anniversary_posts add column if not exists media_kind text;
alter table public.anniversary_posts add column if not exists media_width integer;
alter table public.anniversary_posts add column if not exists media_height integer;
alter table public.anniversary_posts add column if not exists media_duration_seconds numeric;
alter table public.anniversary_posts add column if not exists is_portrait boolean;
alter table public.anniversary_posts add column if not exists final_movie_status text not null default 'unreviewed';
alter table public.anniversary_posts add column if not exists final_movie_note text;

create table if not exists public.anniversary_activity_events (
  id bigint generated by default as identity primary key,
  staff_name text not null,
  event_type text not null,
  event_date date not null default ((timezone('Asia/Tokyo', now()))::date),
  device_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists anniversary_activity_staff_idx on public.anniversary_activity_events(staff_name);
create index if not exists anniversary_activity_type_idx on public.anniversary_activity_events(event_type);
create index if not exists anniversary_activity_created_idx on public.anniversary_activity_events(created_at);
alter table public.anniversary_activity_events enable row level security;
drop policy if exists "anniversary app can create activity events" on public.anniversary_activity_events;
create policy "anniversary app can create activity events" on public.anniversary_activity_events for insert to anon with check (true);
grant insert on table public.anniversary_activity_events to anon;
grant usage, select on sequence public.anniversary_activity_events_id_seq to anon;

create table if not exists public.anniversary_staff_roster (
  id bigint generated by default as identity primary key,
  staff_name text not null unique,
  campus text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.anniversary_staff_roster enable row level security;

create table if not exists public.anniversary_announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text,
  is_active boolean not null default true,
  start_at timestamptz,
  end_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.anniversary_announcements enable row level security;
drop policy if exists "anniversary app can read announcements" on public.anniversary_announcements;
create policy "anniversary app can read announcements" on public.anniversary_announcements
for select to anon using (
  is_active = true
  and (start_at is null or start_at <= now())
  and (end_at is null or end_at >= now())
);
grant select on table public.anniversary_announcements to anon;

-- 管理APIはService Role経由で上記テーブルを操作します。
