-- HOMES 20周年アプリ v5.8 追加設定
-- ログインボーナス / 表彰集計 / KENJI MODE「今日は何の日」追加用
-- Supabase SQL Editor で1回だけ実行してください。

create table if not exists public.anniversary_login_days (
  id bigint generated by default as identity primary key,
  staff_name text not null,
  login_date date not null,
  device_id text,
  created_at timestamptz not null default now(),
  unique (staff_name, login_date)
);

alter table public.anniversary_login_days enable row level security;
drop policy if exists "anniversary app can read login days" on public.anniversary_login_days;
drop policy if exists "anniversary app can create login days" on public.anniversary_login_days;
create policy "anniversary app can read login days"
on public.anniversary_login_days for select to anon using (true);
create policy "anniversary app can create login days"
on public.anniversary_login_days for insert to anon with check (true);
grant select, insert on table public.anniversary_login_days to anon;
grant usage, select on sequence public.anniversary_login_days_id_seq to anon;

create table if not exists public.anniversary_today_events (
  id uuid primary key default gen_random_uuid(),
  month smallint not null check (month between 1 and 12),
  day smallint not null check (day between 1 and 31),
  event_year integer,
  title text not null,
  note text,
  author_name text,
  created_at timestamptz not null default now()
);

alter table public.anniversary_today_events enable row level security;
drop policy if exists "anniversary app can read today events" on public.anniversary_today_events;
drop policy if exists "kenji can create today events" on public.anniversary_today_events;
create policy "anniversary app can read today events"
on public.anniversary_today_events for select to anon using (true);
create policy "kenji can create today events"
on public.anniversary_today_events for insert to anon with check (true);
grant select, insert on table public.anniversary_today_events to anon;

-- Post count is taken from the existing anniversary_posts table.
-- Login counts start accumulating after v5.8 is deployed.
